/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 BP_Martin_C.glb 
*/

import React, { useEffect, useRef } from "react";
import { useCamera, useGLTF } from "@react-three/drei";

export default function Model(props) {
  const obj = useRef();

  // add event listener to highlight dragged objects

  const { nodes, materials } = useGLTF("./furnitures/BP_Martin_C.glb");
  useEffect(() => {
    console.log(nodes);
  }, []);
  return (
    <group {...props} dispose={null} ref={obj}>
      <mesh geometry={nodes.Cube_1.geometry} material={materials.plate} />
      <mesh geometry={nodes.Cube_2.geometry} material={materials.leg} />
    </group>
  );
}

useGLTF.preload("./BP_Martin_C.glb");
