/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 BP_Martin_C.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { furnitureInfo } from "./FurnitureInfo";
import { Vector3 } from "three";

type furnitureProps = { furnitureInfo: furnitureInfo };

export default function Furniture({ furnitureInfo }: furnitureProps) {
  const obj = useRef<any>();

  const handleClick = (e: any) => {
    console.log(e);
  };

  // add event listener to highlight dragged objects
  const position = new Vector3(
    furnitureInfo.position[0],
    furnitureInfo.position[2],
    furnitureInfo.position[1]
  );

  const { nodes, materials } = useGLTF(`./furnitures/${furnitureInfo.file}`);
  const meshs = Object.values(nodes).filter((mesh) => mesh.type === "Mesh");
  useEffect(() => {
    //console.log(nodes);
  }, []);
  return (
    <group dispose={null} ref={obj} position={position} onClick={handleClick}>
      {meshs.map((mesh: any) => (
        <mesh
          key={mesh.uuid}
          geometry={mesh.geometry}
          material={mesh.material}
        />
      ))}
    </group>
  );
}
