/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 BP_Martin_C.glb 
*/

import React, {
  MutableRefObject,
  useCallback,
  useEffect,
  useRef,
  useState,
} from "react";
import { useGLTF } from "@react-three/drei";
import { furnitureInfo } from "./FurnitureInfo";
import { Group, Vector3 } from "three";
import useFurnitureControl from "../hooks/useFurnitureControl";
import { useDispatch, UseDispatch } from "react-redux";
import { createSlice, PayloadAction } from "@reduxjs/toolkit";

const initialState = {
  targetFurniture: "",
};

const furnitureControlSlice = createSlice({
  name: "furnitureControl",
  initialState: initialState,
  reducers: {
    setTargetFurniture: (
      state: typeof initialState,
      action: PayloadAction<string>
    ) => {
      state.targetFurniture = action.payload;
    },
  },
});

const { setTargetFurniture } = furnitureControlSlice.actions;

export const furnitureControlReducer = furnitureControlSlice.reducer;

type furnitureProps = { furnitureInfo: furnitureInfo };

export default function Furniture({ furnitureInfo }: furnitureProps) {
  const obj = useRef<any>();
  const dispatch = useDispatch();

  //const [controlFurniture, setControlFurniture] = useState<string>();

  const handleClick = () => {
    console.log(obj.current.userData.file);
    dispatch(setTargetFurniture(furnitureInfo.file));
  };
  useFurnitureControl(obj.current);

  // add event listener to highlight dragged objects
  const position = new Vector3(...furnitureInfo.position);
  const rotation = furnitureInfo.rotation;

  const { nodes, materials } = useGLTF(`./furnitures/${furnitureInfo.file}`);
  const meshs = Object.values(nodes).filter((mesh) => mesh.type === "Mesh");
  useEffect(() => {
    //console.log(nodes);
  }, []);
  return (
    <group
      dispose={null}
      ref={obj}
      position={position}
      onClick={handleClick}
      rotation={rotation}
      userData={{ file: furnitureInfo.file }}
    >
      {meshs.map((mesh: any) => (
        <mesh
          key={mesh.uuid}
          geometry={mesh.geometry}
          material={mesh.material}
        />
      ))}
    </group>
  );
}
